version: "3.9"
services:
  api-php-fpm:
    build:
      context: ./docker/api-php-fpm
      dockerfile: development/Dockerfile
    container_name: api-php-fpm
    volumes:
      - ./api:/app
      - ./docker/api-php-common/development/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/api-php-common/development/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/api-php-common/development/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db-postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db-postgres
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      CACHE_DRIVER: redis
      REDIS_CLIENT: predis
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      APP_PORT: ${NGINX_HOST_PORT}
    networks:
      - gadbet
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api-php-cli:
    build:
      context: ./docker/api-php-cli
      dockerfile: development/Dockerfile
    container_name: api-php-cli
    volumes:
      - ./api:/app
      - ./docker/api-php-common/development/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/api-php-common/development/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - db-postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db-postgres
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      CACHE_DRIVER: redis
      REDIS_CLIENT: predis
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      APP_PORT: ${NGINX_HOST_PORT}
    networks:
      - gadbet
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api-nginx:
    build:
      context: ./docker/api-nginx
      dockerfile: development/Dockerfile
    container_name: api-nginx
    ports:
      - ${NGINX_HOST_PORT}:80
    volumes:
      - ./api:/app
    networks:
      - gadbet
    depends_on:
      - api-php-fpm

  db-postgres:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - gadbet

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    networks:
      - gadbet
    ports:
      - "1025:1025"
      - "8025:8025"

  centrifugo:
    image: centrifugo/centrifugo:v3.2
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      CENTRIFUGO_TOKEN_HMAC_SECRET_KEY: secret
      CENTRIFUGO_API_KEY: secret
    volumes:
      - ./docker/centrifugo/development/centrifugo:/centrifugo
    ports:
      - "8085:8000"
    container_name: 'centrifugo'
    networks:
      - gadbet
    command: centrifugo --admin --admin_insecure

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - gadbet

networks:
  gadbet:
    name: gadbet
    driver: bridge

volumes:
  postgres_data: