name: Deploy backend on dev01

on:
  push:
    branches:
      - dev
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: dev01
    defaults:
      run:
        working-directory: /home/gadbet/stream-backend

    steps:
      - name: Checkout
        run: git pull
      - name: make up
        run: make up